spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update # ?? ? 'update', ?? ??? ?? ? 'create-drop'
    properties:
      hibernate:
        show_sql: true # ??? SQL ?? ??
        format_sql: true # SQL? ?? ?? ??
  h2:
    console:
      enabled: true # H2 ?? ???
      path: /h2-console # H2 ?? ?? ??

logging:
  level:
    org:
      hibernate:
        SQL: debug # SQL ?? ?? ???

springdoc:
  api-docs:
    path: /v3/api-docs # OpenAPI ?? ??
  swagger-ui:
    path: /swagger-ui.html # Swagger UI ?? ??